mode: MainLine
tag-prefix: gateway/v
branches:
  main:
    increment: Inherit
  release:
    increment: Inherit
  feature:
    regex: ^(feat|fix|improv|chore)[/-]
    commit-message-incrementing: Enabled
    tag: alpha
